### ISSUE TITLE
Quarry not Work

### ISSUE THREAD

**Issue by dauersuche** [Clashsoft-Mods/More-Minerals-Mod#2]
The quarry from Buildcraft4 does not destroy the blocks.

Installed version:
ClashsoftAPI 1.6.2-5.1
More Minerals Mod 1.6.2-4.1

Screenshot:
http://s1.directupload.net/file/d/3424/usawm3s4_png.htm

**Comment by Clashsoft** [comment]
Not sure how to fix this, report this issue on the Buildcraft repository
